# Generated by Django 4.2.5 on 2024-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='application',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='app_set', related_query_name='app', to='auth.permission'),
        ),
    ]
