# Generated by Django 4.2.5 on 2024-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0002_remove_application_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
